/* kmain64.c - the 64-bit kernel's entry point during bring-up.
 *
 * This is deliberately not kernel.c. Porting 40,000 lines of kernel to a
 * new architecture in one step produces a mountain of compiler errors and
 * no way to tell which of them matter; the way this is done instead is to
 * bring the machine up one layer at a time and prove each layer before
 * putting the next one on top of it.
 *
 * What is proved here, in order:
 *   1. long mode is genuinely active (boot64.s)
 *   2. the GDT and TSS load, and the CPU is running on them (gdt64.c)
 *   3. an interrupt can be taken, dispatched to C, and returned from
 *      with every register intact (idt64.c, isr64.s)
 *   4. a handler can rewrite the frame it was given and change where
 *      execution resumes
 *
 * (4) is not a curiosity. It is the whole of Wine's exception dispatch,
 * and Milestone 23 of the 32-bit kernel exists because of it, so the
 * 64-bit interrupt path has to be able to do it from the start rather
 * than discovering later that it cannot. */

#include <stdint.h>
#include "io.h"
#include "serial64.h"
#include "gdt64.h"
#include "idt64.h"
#include "multiboot.h"
#include "pmm64.h"
#include "paging64.h"
#include "kheap64.h"
#include "kstring.h"
#include "syscall64.h"
#include "vmspace64.h"
#include "sched64.h"
#include "elf64.h"
#include "uspace64.h"
#include "pe64.h"
#include "win32_64.h"
#include "initrd64.h"
#include "signal64.h"
#include "ramfs64.h"

static int failures = 0;

/* The stack the CPU switches to when an interrupt arrives in ring 3.
 * Separate from the kernel's own stack because the interrupted kernel
 * stack is not necessarily where the CPU should land. */
static uint8_t ring3_int_stack[16384] __attribute__((aligned(16)));

static void check(const char* what, int ok) {
    if (!ok) failures++;
    serial64_puts(ok ? "NOVARIS64: ok    " : "NOVARIS64: FAIL  ");
    serial64_puts(what);
    serial64_putc('\n');
}

static uint64_t read_cr0(void) {
    uint64_t v; __asm__ __volatile__("mov %%cr0, %0" : "=r"(v)); return v;
}
static uint64_t read_cr3(void) {
    uint64_t v; __asm__ __volatile__("mov %%cr3, %0" : "=r"(v)); return v;
}
static uint64_t read_cr4(void) {
    uint64_t v; __asm__ __volatile__("mov %%cr4, %0" : "=r"(v)); return v;
}
static uint64_t read_msr(uint32_t msr) {
    uint32_t lo, hi;
    __asm__ __volatile__("rdmsr" : "=a"(lo), "=d"(hi) : "c"(msr));
    return ((uint64_t)hi << 32) | lo;
}
static uint16_t read_cs(void) {
    uint16_t v; __asm__ __volatile__("mov %%cs, %0" : "=r"(v)); return v;
}
static uint16_t read_tr(void) {
    uint16_t v; __asm__ __volatile__("str %0" : "=r"(v)); return v;
}
static uint64_t read_cr2(void) {
    uint64_t v; __asm__ __volatile__("mov %%cr2, %0" : "=r"(v)); return v;
}

extern char _kernel_virtual_start[];
extern char _kernel_virtual_end[];
extern char _kernel_physical_start[];
extern char _kernel_physical_end[];

/* Generated by userland/embed64.py from a host-built ELF64 executable. */
extern const unsigned char hello64_elf[];
extern const unsigned long hello64_elf_len;
extern const unsigned char glibc64_elf[];
extern const unsigned long glibc64_elf_len;
extern const unsigned char pe64_exe[];
extern const unsigned long pe64_exe_len;
extern const unsigned char dlllib64_dll[];
extern const unsigned long dlllib64_dll_len;
extern const unsigned char dlluser64_exe[];
extern const unsigned long dlluser64_exe_len;
extern const unsigned char loader64_exe[];
extern const unsigned long loader64_exe_len;
extern const unsigned char thread64_elf[];
extern const unsigned long thread64_elf_len;
extern const unsigned char futex64_elf[];
extern const unsigned long futex64_elf_len;
extern const unsigned char signal64_elf[];
extern const unsigned long signal64_elf_len;
extern const unsigned char fs64_elf[];
extern const unsigned long fs64_elf_len;

/* isr64.s - a load that is allowed to fault, and where to resume if it does. */
extern uint64_t probe_read64(const void* addr);
extern void probe_read64_recover(void);

/* --- what the handlers below record ---------------------------------- */
static volatile int      bp_hits;
static volatile uint64_t bp_rip;

static volatile int      pf_hits;
static volatile uint64_t pf_cr2;
static volatile uint64_t pf_err;
static volatile uint64_t pf_resume_rip;

static void breakpoint_handler(registers64_t* r) {
    bp_hits++;
    bp_rip = r->rip;
    /* #BP is a trap: rip already points past the int3, so returning
     * unchanged resumes at the next instruction. */
}

static volatile uint64_t timer_ticks;

static void timer_handler(registers64_t* r) {
    (void)r;
    timer_ticks++;
}

/* The same interrupt, once there is something to schedule. */
static void sched_timer_handler(registers64_t* r) {
    timer_ticks++;
    sched64_tick(r);
}

/* Once a real program is running, a page fault is a fact to be reported
 * rather than something to resume past. Without this the handler below
 * sends a ring-3 fault to a *kernel* recovery address, which faults
 * immediately, forever - a silent hang with nothing on the serial port,
 * which is exactly how the first attempt at running glibc presented. */
static volatile int pf_diagnose;

static void page_fault_handler(registers64_t* r) {
    pf_hits++;
    pf_cr2 = read_cr2();
    pf_err = r->err_code;

    /* A ring-3 fault with a handler installed is the program's business,
     * not a kernel failure - it is how Wine turns a bad access into a
     * Windows exception. Tried before the diagnostic below, so that a
     * fault with no handler still reports rather than vanishing. */
    if (signal64_deliver(SIG64_SEGV, r, pf_cr2)) return;

    if (pf_diagnose) {
        serial64_puts("\nNOVARIS64: *** page fault in the program\n");
        serial64_puts("NOVARIS64:   cr2=");  serial64_puthex(pf_cr2);
        serial64_puts(" rip=");              serial64_puthex(r->rip);
        serial64_puts("\nNOVARIS64:   err="); serial64_puthex(pf_err);
        serial64_puts(" cs=");               serial64_puthex(r->cs);
        serial64_puts(" rsp=");              serial64_puthex(r->rsp);
        serial64_puts("\nNOVARIS64: *** halted\n");
        for (;;) __asm__ __volatile__("cli; hlt");
    }
    /* #PF is a fault: rip points *at* the instruction that faulted, so
     * returning unchanged would re-run it and fault forever. Send
     * execution to the recovery label instead. */
    r->rip = pf_resume_rip;
}

void kernel_main(uint32_t magic, void* mbi) {
    uint64_t cr0, cr4, efer, rip;
    uint64_t before, after, probed;

    serial64_init();

    cr0  = read_cr0();
    cr4  = read_cr4();
    efer = read_msr(0xC0000080);
    __asm__ __volatile__("lea (%%rip), %0" : "=r"(rip));

    serial64_puts("\nNOVARIS64: ---- long mode bring-up ----\n");

    /* --- layer 1: the mode itself --------------------------------- */
    /* EFER.LMA is set by the CPU when long mode actually goes active. It
     * is the one bit here that is proof rather than assertion. */
    check("EFER.LMA  - long mode is active", (efer & (1ULL << 10)) != 0);
    check("EFER.LME  - long mode is enabled", (efer & (1ULL << 8)) != 0);
    check("CR0.PG    - paging is on",         (cr0 & (1ULL << 31)) != 0);
    check("CR4.PAE   - PAE is on",            (cr4 & (1ULL << 5)) != 0);
    check("CR4.OSFXSR- SSE is usable",        (cr4 & (1ULL << 9)) != 0);
    check("pointers are 8 bytes",             sizeof(void*) == 8);
    check("long is 8 bytes (LP64)",           sizeof(long) == 8);
    check("RIP is in the higher half",        rip >= 0xFFFFFFFF80000000ULL);
    check("multiboot magic is 0x2BADB002",    magic == 0x2BADB002u);
    check("multiboot info pointer is non-NULL", mbi != 0);

    serial64_puts("NOVARIS64: cs      = "); serial64_puthex(read_cs());
    serial64_puts("\nNOVARIS64: rip     = "); serial64_puthex(rip);
    serial64_puts("\nNOVARIS64: cr3     = "); serial64_puthex(read_cr3());
    serial64_puts("\nNOVARIS64: efer    = "); serial64_puthex(efer);
    serial64_puts("\nNOVARIS64: kernel  = ");
    serial64_puthex((uint64_t)_kernel_virtual_start);
    serial64_puts(" .. ");
    serial64_puthex((uint64_t)_kernel_virtual_end);
    serial64_puts("\nNOVARIS64: size    = ");
    serial64_putdec((uint64_t)(_kernel_virtual_end - _kernel_virtual_start));
    serial64_puts(" bytes\n");

    /* --- layer 2: descriptors -------------------------------------- */
    serial64_puts("NOVARIS64: -- descriptors --\n");
    gdt64_install();

    /* Surviving gdt64_flush at all is most of the test: it reloads every
     * segment register and changes cs through a far return, so a wrong
     * descriptor here is a fault rather than a wrong answer. */
    check("GDT loaded, cs is the kernel code selector",
          read_cs() == GDT64_KCODE_SEL);
    check("TSS loaded into the task register",
          read_tr() == GDT64_TSS_SEL);
    check("IST1 (double fault) stack is set",
          gdt64_ist_stack(IST_DOUBLE_FAULT) != 0);
    check("IST2 (NMI) stack is set",
          gdt64_ist_stack(IST_NMI) != 0);

    /* --- layer 3: an interrupt, taken and returned from ------------- */
    serial64_puts("NOVARIS64: -- interrupts --\n");
    idt64_install();
    register_interrupt_handler64(3,  breakpoint_handler);
    register_interrupt_handler64(14, page_fault_handler);

    /* Registers either side of an int3. If the stub's fifteen pushes and
     * pops are not exact mirrors, this is where it shows: a value lands
     * back in the wrong register and the comparison fails. */
    before = 0x0123456789ABCDEFULL;
    __asm__ __volatile__(
        "mov %1, %%r12\n\t"
        "int $3\n\t"
        "mov %%r12, %0"
        : "=r"(after)
        : "r"(before)
        : "r12");

    check("int3 reached a C handler", bp_hits == 1);
    check("execution resumed after int3", 1);
    check("a callee-saved register survived the interrupt", after == before);
    check("the saved rip was in the kernel", bp_rip >= 0xFFFFFFFF80000000ULL);

    /* --- layer 4: a handler that rewrites the frame ----------------- */
    /* 0xFFFF800000000000 is canonical but has no PML4 entry, so reading it
     * is a page fault at a known address. probe_read64 is the faulting
     * instruction and probe_read64_recover is where the handler sends
     * execution instead - both real symbols, for the reason isr64.s
     * explains at length. */
    pf_resume_rip = (uint64_t)&probe_read64_recover;
    probed = probe_read64((const void*)0xFFFF800000000000ULL);

    check("the probe returned the recovery value, not the memory", probed == 0);
    check("a page fault reached a C handler", pf_hits == 1);
    check("cr2 held the address that faulted",
          pf_cr2 == 0xFFFF800000000000ULL);
    check("the fault was a not-present read",
          (pf_err & 0x1) == 0);
    check("the handler rewrote rip and execution resumed there", 1);

    serial64_puts("NOVARIS64: cr2     = "); serial64_puthex(pf_cr2);
    serial64_puts("\nNOVARIS64: pf err  = "); serial64_puthex(pf_err);
    serial64_putc('\n');

    /* --- layer 5: physical frames ---------------------------------- */
    serial64_puts("NOVARIS64: -- physical memory --\n");
    {
        uint64_t kphys_start = (uint64_t)_kernel_physical_start;
        uint64_t kphys_end   = (uint64_t)_kernel_physical_end;
        uint64_t total, free_before, f1, f2, free_after, dbl;

        pmm64_init((const multiboot_info_t*)mbi, kphys_start, kphys_end);

        /* Immediately after, and before anything allocates: the initrd
         * sits in RAM the allocator was just told is free, and it
         * reserves its own pages as part of coming up. */
        initrd64_init((const multiboot_info_t*)mbi);

        check("the frame allocator came up", pmm64_ready());
        total = pmm64_total_frames();
        free_before = pmm64_free_frames();
        check("RAM was found", total > 0);
        check("some of it is free", free_before > 0);
        check("not all of it is free", free_before < total);

        f1 = pmm64_alloc_frame();
        f2 = pmm64_alloc_frame();
        check("a frame was allocated", f1 != 0);
        check("a second frame was allocated", f2 != 0);
        check("the two are different frames", f1 != f2);
        check("frames are page aligned", (f1 % PMM64_FRAME_SIZE) == 0);
        /* The first megabyte and the kernel's own image are the two things
         * that must never be handed out; a bug in the reserve pass shows
         * up here rather than as corruption three milestones later. */
        check("no frame comes from the first megabyte", f1 >= 0x100000ULL);
        check("no frame overlaps the kernel image",
              f1 < kphys_start || f1 >= kphys_end);
        check("no frame overlaps the frame bitmap",
              f1 < pmm64_bitmap_phys() ||
              f1 >= pmm64_bitmap_phys() + pmm64_bitmap_bytes());

        check("allocating two frames used two frames",
              pmm64_free_frames() == free_before - 2);
        pmm64_free_frame(f1);
        pmm64_free_frame(f2);
        free_after = pmm64_free_frames();
        check("freeing them gave both back", free_after == free_before);

        /* Freeing twice is the one error this allocator is asked to
         * notice rather than obey. */
        dbl = pmm64_double_frees();
        pmm64_free_frame(f1);
        check("a double free was counted, not obeyed",
              pmm64_double_frees() == dbl + 1);
        check("and it did not change the free count",
              pmm64_free_frames() == free_after);

        serial64_puts("NOVARIS64: ram top = ");
        serial64_puthex(pmm64_highest_addr());
        serial64_puts("\nNOVARIS64: frames  = ");
        serial64_putdec(total);
        serial64_puts(" total, ");
        serial64_putdec(free_before);
        serial64_puts(" free\n");
        serial64_puts("NOVARIS64: bitmap  = ");
        serial64_puthex(pmm64_bitmap_phys());
        serial64_puts(" .. +");
        serial64_putdec(pmm64_bitmap_bytes());
        serial64_puts(" bytes\n");
    }

    /* --- layer 6: four-level paging --------------------------------- */
    serial64_puts("NOVARIS64: -- paging --\n");
    {
        /* PML4 slot 384. Not 256: that is the address layer 4 above
         * relies on being unmapped, and mapping it here would quietly
         * turn that page-fault test into a test of nothing. */
        const uint64_t TEST_VA = 0xFFFFC00000000000ULL;
        const uint64_t MAGIC   = 0x00C0FFEE5EA51DE5ULL;
        uint64_t frame, got, tables_before;
        volatile uint64_t* p;
        int rc;

        paging64_init();

        /* The self-reference, read through itself: if the recursive
         * address were wrong this load would fault rather than answer. */
        {
            uint64_t* pml4 = paging64_pml4();
            check("the PML4 can be read through its own recursive slot",
                  (pml4[510] & 1) != 0);
            check("the higher half is still mapped in it",
                  (pml4[511] & 1) != 0);
            check("the recursive slot points at the PML4 itself",
                  (pml4[510] & 0x000FFFFFFFFFF000ULL) ==
                  (read_cr3() & 0x000FFFFFFFFFF000ULL));
        }

        tables_before = paging64_tables_allocated();
        frame = pmm64_alloc_frame();
        check("a frame to map was allocated", frame != 0);

        rc = paging64_map(TEST_VA, frame, PAGE64_PRESENT | PAGE64_WRITE);
        check("a fresh 4KB page mapped", rc == PAGING64_OK);
        /* An empty PML4 slot needs a PDPT, a PD and a PT built under it. */
        check("three intermediate tables were built",
              paging64_tables_allocated() == tables_before + 3);

        p = (volatile uint64_t*)TEST_VA;
        *p = MAGIC;
        check("the mapped page is writable and reads back",
              *p == MAGIC);

        rc = paging64_translate(TEST_VA, &got);
        check("translate resolved the mapping", rc == PAGING64_OK);
        check("and resolved it to the frame that was mapped", got == frame);

        /* The strongest form of the same question: the bytes written
         * through the new virtual address must be visible at that
         * physical frame's other address. A mapping that merely does not
         * fault would pass everything above and fail this. */
        if (frame < 0x40000000ULL) {
            volatile uint64_t* through_phys =
                (volatile uint64_t*)(0xFFFFFFFF80000000ULL + frame);
            check("the write landed in that physical frame",
                  *through_phys == MAGIC);
        }

        check("an offset inside the page translates with its offset",
              paging64_translate(TEST_VA + 0x123, &got) == PAGING64_OK &&
              got == frame + 0x123);

        /* The kernel's own text is inside a 2MB page boot64.s built.
         * Refusing to map over it is the honest answer while splitting
         * huge pages is unimplemented. */
        check("mapping over a 2MB page is refused, not corrupted",
              paging64_map(0xFFFFFFFF80000000ULL, frame,
                           PAGE64_PRESENT | PAGE64_WRITE)
              == PAGING64_HUGE_IN_WAY);

        check("an unmapped address does not translate",
              paging64_translate(0xFFFFC00000200000ULL, &got)
              == PAGING64_NOT_MAPPED);

        /* And unmapping must genuinely remove it - checked by faulting on
         * it, using the same probe/recover pair as layer 4. */
        rc = paging64_unmap(TEST_VA);
        check("the page unmapped", rc == PAGING64_OK);
        check("it no longer translates",
              paging64_translate(TEST_VA, &got) == PAGING64_NOT_MAPPED);

        pf_hits = 0;
        pf_resume_rip = (uint64_t)&probe_read64_recover;
        probe_read64((const void*)TEST_VA);
        check("reading it now faults", pf_hits == 1);
        check("and it faulted at that address", pf_cr2 == TEST_VA);

        check("unmapping it twice is refused",
              paging64_unmap(TEST_VA) == PAGING64_NOT_MAPPED);

        pmm64_free_frame(frame);

        serial64_puts("NOVARIS64: tables  = ");
        serial64_putdec(paging64_tables_allocated());
        serial64_puts(" allocated\n");
    }

    /* --- layer 7: the kernel heap ----------------------------------- */
    serial64_puts("NOVARIS64: -- heap --\n");
    {
        const uint64_t PATTERN = 0xA5A5A5A5DEADBEEFULL;
        uint8_t *a, *b, *p1, *p2, *p3;
        uint64_t used, total, blocks_before, blocks_after, dbl;

        kheap64_init();

        a = (uint8_t*)kmalloc64(64);
        check("kmalloc returned memory", a != 0);
        check("and it is 16-byte aligned", ((uint64_t)a % KHEAP64_ALIGN) == 0);

        *(volatile uint64_t*)a = PATTERN;
        check("the allocation is writable and reads back",
              *(volatile uint64_t*)a == PATTERN);

        b = (uint8_t*)kmalloc64(64);
        check("a second allocation succeeded", b != 0);
        check("the two do not overlap", b >= a + 64 || a >= b + 64);
        /* 32 bytes of header + a 64-byte payload: the next block starts
         * 96 bytes on. Asserting the exact layout is what makes the
         * coalescing test below mean anything. */
        check("blocks are laid out end to end", b == a + 96);

        kheap64_stats(&used, &total);
        check("stats report memory in use", used > 0);
        check("stats report at least the initial heap mapped",
              total >= KHEAP64_INITIAL - PAGE64_SIZE);

        kfree64(a);
        kfree64(b);

        dbl = kheap64_double_frees();
        kfree64(a);
        check("a double free was counted, not obeyed",
              kheap64_double_frees() == dbl + 1);

        /* Coalescing, observed rather than asserted by the allocator
         * about itself: three adjacent blocks freed have to collapse back
         * into the block they were carved from, leaving the free list
         * exactly as long as it was before. An allocator that only marks
         * blocks unused would leave three more. */
        blocks_before = kheap64_free_blocks();
        p1 = (uint8_t*)kmalloc64(64);
        p2 = (uint8_t*)kmalloc64(64);
        p3 = (uint8_t*)kmalloc64(64);
        check("three consecutive blocks are adjacent",
              p2 == p1 + 96 && p3 == p2 + 96);
        kfree64(p2);
        kfree64(p1);
        kfree64(p3);
        blocks_after = kheap64_free_blocks();
        check("freeing them merged them back into one block",
              blocks_after == blocks_before);

        /* Bigger than the initial heap, so the growth path runs. */
        {
            uint8_t* big = (uint8_t*)kmalloc64(128 * 1024);
            check("an allocation larger than the heap grew it", big != 0);
            if (big) {
                big[0] = 1;
                big[128 * 1024 - 1] = 2;
                check("the far end of a grown allocation is mapped",
                      big[0] == 1 && big[128 * 1024 - 1] == 2);
                kfree64(big);
            }
        }

        /* The point of the rewrite. kheap.c walks every block, used or
         * free, so N allocations cost N^2/2 steps - 500,000 at N=1000.
         * Walking only the free list makes it linear. The bound below is
         * deliberately loose; what it rules out is the quadratic term. */
        {
            const uint64_t N = 1000;
            uint64_t steps0, calls0, steps1, calls1;
            void** ptrs = (void**)kmalloc64(N * sizeof(void*));

            check("room for the pointer array", ptrs != 0);
            if (ptrs) {
                kheap64_walk_stats(&steps0, &calls0);
                for (uint64_t i = 0; i < N; i++) ptrs[i] = kmalloc64(32);
                kheap64_walk_stats(&steps1, &calls1);

                check("every allocation in the run succeeded",
                      ptrs[0] != 0 && ptrs[N - 1] != 0);
                check("the run made N calls", calls1 - calls0 == N);
                check("the allocator is linear, not quadratic",
                      steps1 - steps0 < N * 8);

                serial64_puts("NOVARIS64: walk    = ");
                serial64_putdec(steps1 - steps0);
                serial64_puts(" steps for ");
                serial64_putdec(N);
                serial64_puts(" allocations (quadratic would be ~");
                serial64_putdec(N * N / 2);
                serial64_puts(")\n");

                for (uint64_t i = 0; i < N; i++) kfree64(ptrs[i]);
                kfree64(ptrs);
            }
        }

        kheap64_stats(&used, &total);
        serial64_puts("NOVARIS64: heap    = ");
        serial64_putdec(used);
        serial64_puts(" used / ");
        serial64_putdec(total);
        serial64_puts(" mapped, ");
        serial64_putdec(kheap64_free_blocks());
        serial64_puts(" free blocks\n");
    }

    /* --- layer 8: kstring, on a 64-bit target ----------------------- */
    /* kstring.c is now shared with the 32-bit tree rather than forked:
     * its size parameters became size_t, which is the same type on i386
     * and the right one here. These check that the shared file behaves on
     * this target - kstrlen in particular now returns size_t. */
    serial64_puts("NOVARIS64: -- kstring --\n");
    {
        char buf[64];
        const char* src = "novaris";

        check("kstrlen counts", kstrlen(src) == 7);
        check("kstrlen returns a 64-bit size_t here",
              sizeof(kstrlen(src)) == 8);

        kmemset(buf, 0, sizeof(buf));
        kmemcpy(buf, src, 8);
        check("kmemcpy copied", kstrcmp(buf, "novaris") == 0);
        check("kmemcmp agrees", kmemcmp(buf, src, 8) == 0);

        kstrlcpy(buf, "truncate me", 6);
        check("kstrlcpy bounds and terminates",
              kstrcmp(buf, "trunc") == 0);

        /* kdiv64 uses a 32-bit DIV, which is legal in long mode. It is
         * only needed on i386, where a 64-bit divide would call libgcc,
         * but it has to still be correct if it is going to be compiled. */
        {
            uint32_t rem = 0;
            uint64_t q = kdiv64(1000000007ULL, 1000U, &rem);
            check("kdiv64 divides", q == 1000000ULL && rem == 7U);
        }
    }

    /* --- layer 9: an IRQ that lands where the IDT expects ----------- */
    /* This is the layer that found the bug. The IDT has always installed
     * its IRQ gates at 32-47, but nothing remapped the 8259s, so the
     * hardware was still delivering IRQ0 to vector 8 - which is #DF. No
     * previous milestone noticed because none of them ever set IF. */
    serial64_puts("NOVARIS64: -- timer --\n");
    {
        const uint32_t divisor = 1193182u / 1000u;   /* ~1kHz */
        uint64_t spins;

        register_interrupt_handler64(32, timer_handler);

        outb(0x43, 0x36);                    /* channel 0, lo/hi, mode 3 */
        outb(0x40, (uint8_t)(divisor & 0xFF));
        outb(0x40, (uint8_t)(divisor >> 8));

        idt64_irq_set_mask(0, 0);
        __asm__ __volatile__("sti");

        /* Bounded, so a machine where this never arrives fails the test
         * rather than hanging until the harness kills it. */
        for (spins = 0; spins < 50000000ULL && timer_ticks < 3; spins++)
            __asm__ __volatile__("pause");

        __asm__ __volatile__("cli");

        check("the timer interrupt arrived at vector 32", timer_ticks >= 3);
        /* If the remap had not happened, the first tick would have been
         * taken as #DF and the machine would already have halted, so
         * reaching this line at all is half the result. */
        check("the machine survived taking interrupts",
              spins < 50000000ULL);

        /* Masked again before ring 3 below, so that test is deterministic
         * rather than depending on whether a tick happens to land inside
         * its few microseconds. Taking an interrupt *while in ring 3* is
         * a different path - it switches to the TSS's rsp0 - and it is
         * not exercised yet; the scheduler in item 3 is what will need
         * it and what should test it. */
        idt64_irq_set_mask(0, 1);

        serial64_puts("NOVARIS64: ticks   = ");
        serial64_putdec(timer_ticks);
        serial64_putc('\n');
    }

    /* --- layer 10: ring 3, and a syscall that comes back ------------ */
    serial64_puts("NOVARIS64: -- ring 3 --\n");
    {
        /* PML4 slot 224. Not one of the low addresses: slot 0 is still
         * the boot identity map, built from 2MB pages, so anything under
         * a gigabyte would come back HUGE_IN_WAY. */
        const uint64_t UCODE_VA  = 0x0000700000000000ULL;
        const uint64_t USTACK_VA = 0x0000700000010000ULL;
        uint64_t code_frame, stack_frame, code_len;
        int rc_code, rc_stack;

        code_len = (uint64_t)(user_test_code_end - user_test_code);
        check("the ring-3 program fits in a page",
              code_len > 0 && code_len < PAGE64_SIZE);

        /* An interrupt taken in ring 3 switches to the stack in the TSS.
         * Without this the first one triple-faults, and it would be the
         * timer rather than anything this test does. */
        gdt64_set_kernel_stack((uint64_t)&ring3_int_stack[sizeof(ring3_int_stack)]);
        syscall64_init();

        code_frame  = pmm64_alloc_frame();
        stack_frame = pmm64_alloc_frame();
        check("frames for the program and its stack",
              code_frame != 0 && stack_frame != 0);

        /* Copied through the physical window rather than through the
         * user mapping, so the code page never has to be writable. */
        kmemcpy((void*)(0xFFFFFFFF80000000ULL + code_frame),
                user_test_code, code_len);

        rc_code  = paging64_map(UCODE_VA, code_frame,
                                PAGE64_PRESENT | PAGE64_USER);
        rc_stack = paging64_map(USTACK_VA, stack_frame,
                                PAGE64_PRESENT | PAGE64_WRITE | PAGE64_USER);
        check("the program mapped as user-readable", rc_code == PAGING64_OK);
        check("its stack mapped as user-writable", rc_stack == PAGING64_OK);

        /* Everything above this line is setup. This is the line that
         * either returns or hangs the machine. */
        enter_user_mode64(UCODE_VA, USTACK_VA + PAGE64_SIZE, 0);

        check("ring 3 was entered and returned", syscall64_count() == 2);
        /* The program read its own CS and handed it over. 0x23 is the
         * user code selector with RPL 3, and it is the one value here
         * that ring 0 could not have produced: the same code running at
         * ring 0 would have reported 0x08. */
        check("the program really was at ring 3 (CS = 0x23)",
              syscall64_last_arg() == 0x23);
        /* And it resumed after the first syscall with the value the
         * kernel returned, which is what proves SYSRET went back rather
         * than the program simply never continuing. */
        check("SYSRET returned to ring 3 with the result",
              syscall64_exit_code() == 0x23 + 0x1111);

        serial64_puts("NOVARIS64: user cs = ");
        serial64_puthex(syscall64_last_arg());
        serial64_puts("\nNOVARIS64: exit   = ");
        serial64_puthex(syscall64_exit_code());
        serial64_puts("\nNOVARIS64: calls  = ");
        serial64_putdec(syscall64_count());
        serial64_putc('\n');

        paging64_unmap(UCODE_VA);
        paging64_unmap(USTACK_VA);
        pmm64_free_frame(code_frame);
        pmm64_free_frame(stack_frame);
    }

    /* --- layer 11: two address spaces ------------------------------- */
    serial64_puts("NOVARIS64: -- address spaces --\n");
    {
        /* PML4 slot 192: the low half, so it belongs to the space rather
         * than to the kernel, which is the whole point of the test. */
        const uint64_t VA = 0x0000600000000000ULL;
        const uint64_t VAL_A = 0xAAAAAAAA11111111ULL;
        const uint64_t VAL_B = 0xBBBBBBBB22222222ULL;
        vmspace64_t kspace, warm, a, b;
        uint64_t fa, fb, free_before, free_after, got;

        vmspace64_kernel_space(&kspace);

        /* One space created and destroyed before the frames are counted.
         * The first create maps a scratch page, and the kernel-half page
         * tables that produces are permanent and shared - counting from
         * before them would look like a leak that is not one. */
        if (vmspace64_create(&warm)) vmspace64_destroy(&warm);
        free_before = pmm64_free_frames();

        check("space A was created", vmspace64_create(&a) != 0);
        check("space B was created", vmspace64_create(&b) != 0);
        check("they are distinct spaces", a.pml4_phys != b.pml4_phys);
        check("and neither is the kernel's",
              a.pml4_phys != kspace.pml4_phys &&
              b.pml4_phys != kspace.pml4_phys);

        fa = pmm64_alloc_frame();
        fb = pmm64_alloc_frame();
        check("a frame for each", fa != 0 && fb != 0 && fa != fb);

        check("one address mapped in A",
              vmspace64_map(&a, VA, fa, PAGE64_PRESENT | PAGE64_WRITE)
              == PAGING64_OK);
        check("the same address mapped in B, to a different frame",
              vmspace64_map(&b, VA, fb, PAGE64_PRESENT | PAGE64_WRITE)
              == PAGING64_OK);

        /* The actual question: does one address mean two different things
         * depending on which space is loaded. */
        vmspace64_switch(&a);
        *(volatile uint64_t*)VA = VAL_A;
        vmspace64_switch(&b);
        *(volatile uint64_t*)VA = VAL_B;
        check("B reads back its own value", *(volatile uint64_t*)VA == VAL_B);
        vmspace64_switch(&a);
        check("A still reads its own, at the very same address",
              *(volatile uint64_t*)VA == VAL_A);

        vmspace64_switch(&kspace);
        check("and the address means nothing in the kernel's space",
              paging64_translate(VA, &got) == PAGING64_NOT_MAPPED);

        /* The kernel survived three CR3 loads, which it only can because
         * its half of every space is the same half. */
        {
            void* p = kmalloc64(64);
            check("the kernel still works after switching back", p != 0);
            kfree64(p);
        }

        vmspace64_destroy(&a);
        vmspace64_destroy(&b);
        pmm64_free_frame(fa);
        pmm64_free_frame(fb);

        free_after = pmm64_free_frames();
        check("destroying both spaces gave every frame back",
              free_after == free_before);

        serial64_puts("NOVARIS64: frames  = ");
        serial64_putdec(free_before);
        serial64_puts(" free before, ");
        serial64_putdec(free_after);
        serial64_puts(" after\n");
    }

    /* --- layer 12: a ring-3 program in its own address space -------- */
    /* Layers 10 and 11 separately: ring 3 works, and spaces isolate.
     * This is both at once, which is what a process actually is - user
     * pages that exist only in its own low half, kernel reachable from
     * inside it because the high half is shared. */
    serial64_puts("NOVARIS64: -- a program in its own space --\n");
    {
        const uint64_t UCODE_VA  = 0x0000700000000000ULL;
        const uint64_t USTACK_VA = 0x0000700000010000ULL;
        vmspace64_t kspace, proc;
        uint64_t code_frame, stack_frame, code_len, got;
        uint64_t calls_before = syscall64_count();

        vmspace64_kernel_space(&kspace);
        code_len = (uint64_t)(user_test_code_end - user_test_code);

        check("a space for the program", vmspace64_create(&proc) != 0);
        code_frame  = pmm64_alloc_frame();
        stack_frame = pmm64_alloc_frame();
        check("frames for it", code_frame != 0 && stack_frame != 0);

        kmemcpy((void*)(0xFFFFFFFF80000000ULL + code_frame),
                user_test_code, code_len);

        check("its code mapped into its own space",
              vmspace64_map(&proc, UCODE_VA, code_frame,
                            PAGE64_PRESENT | PAGE64_USER) == PAGING64_OK);
        check("its stack too",
              vmspace64_map(&proc, USTACK_VA, stack_frame,
                            PAGE64_PRESENT | PAGE64_WRITE | PAGE64_USER)
              == PAGING64_OK);

        /* Nothing of the program is visible from the kernel's space. */
        check("none of it is mapped in the kernel's space",
              paging64_translate(UCODE_VA, &got) == PAGING64_NOT_MAPPED);

        vmspace64_switch(&proc);
        enter_user_mode64(UCODE_VA, USTACK_VA + PAGE64_SIZE, 0);
        vmspace64_switch(&kspace);

        check("it ran and exited", syscall64_count() == calls_before + 2);
        check("it ran at ring 3", syscall64_last_arg() == 0x23);
        check("and the syscall found the kernel from inside its space",
              syscall64_exit_code() == 0x23 + 0x1111);

        vmspace64_destroy(&proc);
        pmm64_free_frame(code_frame);
        pmm64_free_frame(stack_frame);
    }

    /* --- layer 13: two tasks, preempted by the timer ---------------- */
    /* The first thing in this tree to be interrupted while at CPL 3, and
     * therefore the first use of the TSS's rsp0. Everything below rests
     * on one property of the interrupt path: by the time a handler runs,
     * the whole user-visible state of the interrupted task is already a
     * registers64_t in memory, so switching tasks is copying structs. */
    serial64_puts("NOVARIS64: -- preemption --\n");
    {
        const uint64_t UCODE_VA  = 0x0000700000000000ULL;
        const uint64_t USTACK_VA = 0x0000700000010000ULL;
        const uint64_t UDATA_VA  = 0x0000700000020000ULL;
        vmspace64_t kspace, space[2];
        uint64_t data_frame[2];
        uint64_t code_len, exit_off, counters[2];
        int i, ok = 1;

        vmspace64_kernel_space(&kspace);
        code_len = (uint64_t)(task_count_code_end - task_count_code);
        exit_off = (uint64_t)(task_count_exit - task_count_code);
        check("the counting program fits in a page", code_len < PAGE64_SIZE);

        sched64_init();

        for (i = 0; i < 2; i++) {
            uint64_t code_frame, stack_frame;

            if (!vmspace64_create(&space[i])) { ok = 0; break; }
            code_frame    = pmm64_alloc_frame();
            stack_frame   = pmm64_alloc_frame();
            data_frame[i] = pmm64_alloc_frame();
            if (!code_frame || !stack_frame || !data_frame[i]) { ok = 0; break; }

            kmemcpy((void*)(0xFFFFFFFF80000000ULL + code_frame),
                    task_count_code, code_len);
            /* The counter starts at zero, and the kernel reads it back
             * through this same window once the run is over. */
            *(volatile uint64_t*)(0xFFFFFFFF80000000ULL + data_frame[i]) = 0;

            vmspace64_map(&space[i], UCODE_VA, code_frame,
                          PAGE64_PRESENT | PAGE64_USER);
            vmspace64_map(&space[i], USTACK_VA, stack_frame,
                          PAGE64_PRESENT | PAGE64_WRITE | PAGE64_USER);
            vmspace64_map(&space[i], UDATA_VA, data_frame[i],
                          PAGE64_PRESENT | PAGE64_WRITE | PAGE64_USER);

            /* Identical entry point, stack and counter address in both -
             * the two tasks differ only in which address space they run
             * in, which is what makes the counters below mean something. */
            sched64_add(UCODE_VA, USTACK_VA + PAGE64_SIZE, UDATA_VA,
                        &space[i]);
        }
        check("two tasks, each in its own address space", ok);

        if (ok) {
            sched64_set_current(0);
            /* Ends the run after a known number of *ticks*. Counting
             * iterations inside the task instead would make the test
             * depend on how fast the emulator happens to be. */
            sched64_stop_after(8, UCODE_VA + exit_off);

            register_interrupt_handler64(32, sched_timer_handler);
            idt64_irq_set_mask(0, 0);

            vmspace64_switch(&space[0]);
            enter_user_mode64(UCODE_VA, USTACK_VA + PAGE64_SIZE, UDATA_VA);
            /* Returned because one of the two made an exit call. The
             * syscall path cleared IF on the way in and never restored
             * it, so no tick can land between here and the mask below. */
            vmspace64_switch(&kspace);
            idt64_irq_set_mask(0, 1);

            for (i = 0; i < 2; i++)
                counters[i] = *(volatile uint64_t*)
                    (0xFFFFFFFF80000000ULL + data_frame[i]);

            check("the timer switched between them",
                  sched64_switches() >= 8);
            /* Both counters non-zero is the result. One task running
             * would leave the other at exactly zero, and each counter
             * lives in a frame only its own space can reach. */
            check("the first task ran", counters[0] > 0);
            check("the second task ran too", counters[1] > 0);
            check("they counted into different physical frames",
                  data_frame[0] != data_frame[1]);
            check("the task that exited reported its own count",
                  syscall64_exit_code() == counters[0] ||
                  syscall64_exit_code() == counters[1]);

            /* Leave no live tasks behind. Since Milestone 56 exit(2)
             * hands the CPU to a surviving sibling rather than ending
             * the run, so a stale task here would capture the *next*
             * layer's exit and never give control back. */
            sched64_init();

            serial64_puts("NOVARIS64: switches= ");
            serial64_putdec(sched64_switches());
            serial64_puts(", task0 = ");
            serial64_putdec(counters[0]);
            serial64_puts(", task1 = ");
            serial64_putdec(counters[1]);
            serial64_putc('\n');
        }
    }

    /* --- layer 14: a real Linux x86-64 executable ------------------- */
    /* The first thing here that was not written for Novaris. It is an
     * ordinary static ELF64, built by the host toolchain, using Linux's
     * x86-64 syscall numbers and register convention - so if it prints,
     * what this kernel implements is Linux's ABI rather than a private
     * convention shaped like it. That property is the whole reason the
     * 32-bit tree can run real glibc and real Wine. */
    serial64_puts("NOVARIS64: -- a real Linux binary --\n");
    {
        /* Slot 255: the top of the low half, well clear of wherever ld
         * decided to put the program. */
        const uint64_t USTACK_VA = 0x00007FFFFFFFE000ULL;
        vmspace64_t kspace, space;
        elf64_info_t info;
        uint64_t entry, stack_frame;
        uint64_t written_before = syscall64_bytes_written();
        int rc;

        vmspace64_kernel_space(&kspace);
        check("a space for the program", vmspace64_create(&space) != 0);

        rc = elf64_load(hello64_elf, hello64_elf_len, &space, &info);
        entry = info.entry;
        check("the ELF64 loaded", rc == ELF64_OK);
        check("it has an entry point", entry != 0);
        check("and something was mapped for it", elf64_pages_mapped() >= 1);

        stack_frame = pmm64_alloc_frame();
        check("a stack for it", stack_frame != 0);
        check("its stack mapped",
              vmspace64_map(&space, USTACK_VA, stack_frame,
                            PAGE64_PRESENT | PAGE64_WRITE | PAGE64_USER)
              == PAGING64_OK);

        serial64_puts("NOVARIS64: entry   = ");
        serial64_puthex(entry);
        serial64_puts("\nNOVARIS64: --- its output follows ---\n");

        vmspace64_switch(&space);
        enter_user_mode64(entry, USTACK_VA + PAGE64_SIZE, 0);
        vmspace64_switch(&kspace);

        serial64_puts("NOVARIS64: --- end of its output ---\n");

        /* write(2) reached the kernel with a ring-3 pointer that the
         * kernel could read, which it only can because the high half is
         * shared and the syscall never left the caller's space. */
        check("it wrote to stdout",
              syscall64_bytes_written() > written_before);
        /* 42 is the status the program passes to exit(2). Anything else
         * ending the run - a fault, the scheduler - would not produce it. */
        check("and it exited with its own status, 42",
              syscall64_exit_code() == 42);

        serial64_puts("NOVARIS64: wrote   = ");
        serial64_putdec(syscall64_bytes_written() - written_before);
        serial64_puts(" bytes, exit ");
        serial64_putdec(syscall64_exit_code());
        serial64_putc('\n');
    }

    /* --- layer 15: real glibc ---------------------------------------- */
    /* hello64.s issues three syscalls by hand. This one is an ordinary C
     * program compiled by the host against real glibc, so before main
     * runs it sets up thread-local storage, reads its own program
     * headers out of the auxiliary vector, initialises malloc and builds
     * a buffered stdio stream. Every one of those is a demand on this
     * kernel's ABI, and glibc was compiled long before Novaris existed,
     * so none of them are negotiable. */
    serial64_puts("NOVARIS64: -- real glibc --\n");
    {
        /* 64KB of stack: glibc's startup uses far more of it than a
         * hand-written program does. */
        const uint64_t STACK_PAGES = 16;
        const uint64_t STACK_TOP   = 0x00007FFFFFFF0000ULL;
        vmspace64_t kspace, space;
        elf64_info_t info;
        uint64_t rsp, i;
        uint64_t written_before = syscall64_bytes_written();
        uint64_t enosys_before  = syscall64_unimplemented_count();
        int rc, stack_ok = 1;

        vmspace64_kernel_space(&kspace);
        check("a space for glibc", vmspace64_create(&space) != 0);

        rc = elf64_load(glibc64_elf, glibc64_elf_len, &space, &info);
        check("the glibc binary loaded", rc == ELF64_OK);
        check("it reported where its program headers went",
              info.phdr_va != 0);
        check("and where its heap should start", info.brk_start != 0);

        for (i = 0; i < STACK_PAGES; i++) {
            uint64_t f = pmm64_alloc_frame();
            if (!f || vmspace64_map(&space,
                                    STACK_TOP - (i + 1) * PAGE64_SIZE, f,
                                    PAGE64_PRESENT | PAGE64_WRITE |
                                    PAGE64_USER) != PAGING64_OK)
                stack_ok = 0;
        }
        check("a stack for it", stack_ok);

        uspace64_reset(&space, info.brk_start);
        rsp = uspace64_build_stack(&space, STACK_TOP, STACK_PAGES,
                                   "/hello_glibc64", &info);
        check("argc/argv/envp/auxv built on it", rsp != 0);
        check("and the stack pointer is 16-byte aligned", (rsp % 16) == 0);

        serial64_puts("NOVARIS64: entry   = ");
        serial64_puthex(info.entry);
        serial64_puts("\nNOVARIS64: phdr    = ");
        serial64_puthex(info.phdr_va);
        serial64_puts(" x");
        serial64_putdec(info.phnum);
        serial64_puts("\nNOVARIS64: brk     = ");
        serial64_puthex(info.brk_start);
        serial64_puts("\nNOVARIS64: --- its output follows ---\n");

        /* Tracing stays off: it prints a line per call, which would bury
         * the program's own output in the transcript the differential
         * compares. syscall64_set_trace(1) is how the startup sequence
         * was worked out in the first place, there being no strace. */
        pf_diagnose = 1;
        vmspace64_switch(&space);
        enter_user_mode64(info.entry, rsp, 0);
        vmspace64_switch(&kspace);
        pf_diagnose = 0;

        serial64_puts("NOVARIS64: --- end of its output ---\n");

        check("glibc reached main and printed",
              syscall64_bytes_written() > written_before);
        check("and the program returned its own status, 7",
              syscall64_exit_code() == 7);

        serial64_puts("NOVARIS64: wrote   = ");
        serial64_putdec(syscall64_bytes_written() - written_before);
        serial64_puts(" bytes, exit ");
        serial64_putdec(syscall64_exit_code());
        serial64_puts(", pages ");
        serial64_putdec(uspace64_pages_allocated());
        serial64_puts(", enosys ");
        serial64_putdec(syscall64_unimplemented_count() - enosys_before);
        serial64_putc('\n');
    }

    /* --- layer 16: a 64-bit Windows executable ---------------------- */
    /* The format chrome.exe is in. Built by mingw, importing from
     * kernel32, linked at a Windows image base, and never told what it
     * would run on - the same relationship the glibc binary above has
     * with Linux. */
    serial64_puts("NOVARIS64: -- a 64-bit Windows PE --\n");
    {
        const uint64_t STACK_TOP   = 0x00007FFFFFFF0000ULL;
        const uint64_t STACK_PAGES = 8;
        vmspace64_t kspace, space;
        pe64_info_t info;
        uint64_t rsp, i;
        uint64_t written_before = win32_64_bytes_written();
        int rc, stack_ok = 1;

        vmspace64_kernel_space(&kspace);
        check("a space for the PE", vmspace64_create(&space) != 0);

        rc = pe64_load(pe64_exe, pe64_exe_len, &space, &info);
        check("the PE32+ loaded", rc == PE64_OK);
        /* mingw links at 0x140000000, the default for a 64-bit image,
         * and this one carries no relocations - so it has to go exactly
         * there or its absolute addresses are wrong. */
        check("at the image base it asked for",
              info.image_base == 0x140000000ULL);
        check("its entry point is inside the image",
              info.entry > info.image_base &&
              info.entry < info.image_base + info.image_size);
        check("all three kernel32 imports were bound", info.imports == 3);

        for (i = 0; i < STACK_PAGES; i++) {
            uint64_t f = pmm64_alloc_frame();
            if (!f || vmspace64_map(&space,
                                    STACK_TOP - (i + 1) * PAGE64_SIZE, f,
                                    PAGE64_PRESENT | PAGE64_WRITE |
                                    PAGE64_USER) != PAGING64_OK)
                stack_ok = 0;
        }
        check("a stack for it", stack_ok);

        /* Entered as though it had been called: the Windows ABI expects
         * rsp to be 8 past a 16-byte boundary at a function's first
         * instruction, because a return address is sitting there. Get
         * this wrong and the first `movaps` in the program faults on an
         * alignment it was entitled to assume. */
        rsp = STACK_TOP - 8;
        check("the stack pointer is where a call would leave it",
              (rsp % 16) == 8);

        serial64_puts("NOVARIS64: base    = ");
        serial64_puthex(info.image_base);
        serial64_puts("\nNOVARIS64: entry   = ");
        serial64_puthex(info.entry);
        serial64_puts("\nNOVARIS64: imports = ");
        serial64_putdec(info.imports);
        serial64_puts(", relocs ");
        serial64_putdec(info.relocs);
        serial64_puts(", pages ");
        serial64_putdec(info.pages);
        serial64_puts("\nNOVARIS64: --- its output follows ---\n");

        pf_diagnose = 1;
        vmspace64_switch(&space);
        enter_user_mode64(info.entry, rsp, 0);
        vmspace64_switch(&kspace);
        pf_diagnose = 0;

        serial64_puts("NOVARIS64: --- end of its output ---\n");

        /* Reaching WriteFile at all means the import thunk shuffled the
         * Windows argument registers into the kernel's and came back. */
        check("it wrote through WriteFile",
              win32_64_bytes_written() > written_before);
        check("and ExitProcess ended it with its own status, 3",
              syscall64_exit_code() == 3);

        serial64_puts("NOVARIS64: wrote   = ");
        serial64_putdec(win32_64_bytes_written() - written_before);
        serial64_puts(" bytes, exit ");
        serial64_putdec(syscall64_exit_code());
        serial64_putc('\n');
    }

    /* --- layer 17: a PE that ships its own DLL ---------------------- */
    /* chrome.exe's shape: a small executable whose real work is in a
     * library beside it. Two things get proved here that layer 16 could
     * not - resolving an import against a real export table, and moving
     * an image away from the base it was linked at. */
    serial64_puts("NOVARIS64: -- a PE with its own DLL --\n");
    {
        /* Forced, not incidental. Loading the DLL where it asked would
         * leave the relocation code untested, and the first image that
         * genuinely needs it will be chrome.exe. */
        const uint64_t DLL_BIAS    = 0x10000000ULL;
        const uint64_t STACK_TOP   = 0x00007FFFFFFF0000ULL;
        const uint64_t STACK_PAGES = 8;
        vmspace64_t kspace, space;
        pe64_info_t dll, exe;
        uint64_t rsp, i;
        uint64_t written_before = win32_64_bytes_written();
        int rc_dll, rc_exe, stack_ok = 1;

        vmspace64_kernel_space(&kspace);
        pe64_reset_modules();
        check("a space for the pair", vmspace64_create(&space) != 0);

        rc_dll = pe64_load_dll(dlllib64_dll, dlllib64_dll_len, &space,
                               "dlllib64.dll", DLL_BIAS, &dll);
        check("the DLL loaded", rc_dll == PE64_OK);
        check("it was moved off its preferred base", dll.relocs > 0);
        check("and it is registered as a module", pe64_module_count() == 1);
        /* The DLL imports from kernel32 itself, so it needed thunks of
         * its own before anything could call into it. */
        check("its own kernel32 imports were bound", dll.imports >= 2);

        rc_exe = pe64_load(dlluser64_exe, dlluser64_exe_len, &space, &exe);
        check("the executable loaded", rc_exe == PE64_OK);
        /* Two from the DLL, three from kernel32. The DLL's two resolve
         * to addresses inside it; kernel32's three become thunks. */
        check("all five of its imports were bound", exe.imports == 5);

        for (i = 0; i < STACK_PAGES; i++) {
            uint64_t f = pmm64_alloc_frame();
            if (!f || vmspace64_map(&space,
                                    STACK_TOP - (i + 1) * PAGE64_SIZE, f,
                                    PAGE64_PRESENT | PAGE64_WRITE |
                                    PAGE64_USER) != PAGING64_OK)
                stack_ok = 0;
        }
        check("a stack for it", stack_ok);
        rsp = STACK_TOP - 8;

        serial64_puts("NOVARIS64: dll     = ");
        serial64_puthex(dll.image_base);
        serial64_puts(", relocs ");
        serial64_putdec(dll.relocs);
        serial64_puts("\nNOVARIS64: exe     = ");
        serial64_puthex(exe.image_base);
        serial64_puts("\nNOVARIS64: --- its output follows ---\n");

        pf_diagnose = 1;
        vmspace64_switch(&space);
        enter_user_mode64(exe.entry, rsp, 0);
        vmspace64_switch(&kspace);
        pf_diagnose = 0;

        serial64_puts("NOVARIS64: --- end of its output ---\n");

        check("the DLL's code ran",
              win32_64_bytes_written() > written_before);
        /* The executable exits 5 only if the DLL returned exactly 1234.
         * 99 would mean the call arrived but the convention is wrong,
         * which is a different bug from the call not arriving at all. */
        check("and returned the right value across the call",
              syscall64_exit_code() == 5);

        serial64_puts("NOVARIS64: exit    = ");
        serial64_putdec(syscall64_exit_code());
        serial64_putc('\n');
    }

    /* --- layer 18: a DLL loaded from a file, by name, at run time ---- */
    /* Everything before this had its libraries resolved before it
     * started, from bytes compiled into the kernel. This program names a
     * file, gets back a module, and finds a function in it - which is
     * what LoadLibrary is, and the shape chrome.exe depends on:
     * chrome_elf.dll *loads* chrome.dll rather than importing it. */
    serial64_puts("NOVARIS64: -- LoadLibrary from a file --\n");
    {
        const uint64_t STACK_TOP   = 0x00007FFFFFFF0000ULL;
        const uint64_t STACK_PAGES = 8;
        vmspace64_t kspace, space;
        pe64_info_t exe;
        uint64_t rsp, i;
        uint64_t loads_before = win32_64_loads();
        int rc, stack_ok = 1;

        check("the initrd was found and parsed",
              initrd64_file_count() > 0);
        {
            const void* probe;
            uint64_t plen = 0;
            check("and dlllib64.dll is in it",
                  initrd64_open("dlllib64.dll", &probe, &plen)
                  == INITRD64_OK && plen > 0);
        }

        vmspace64_kernel_space(&kspace);
        pe64_reset_modules();
        check("a space for the program", vmspace64_create(&space) != 0);

        rc = pe64_load(loader64_exe, loader64_exe_len, &space, &exe);
        check("the program loaded", rc == PE64_OK);
        /* Its import table names kernel32 only - GetStdHandle, WriteFile,
         * LoadLibraryA, GetProcAddress, ExitProcess. The DLL it uses is
         * not in there at all. */
        check("it imports no DLL of its own", pe64_module_count() == 0);

        for (i = 0; i < STACK_PAGES; i++) {
            uint64_t f = pmm64_alloc_frame();
            if (!f || vmspace64_map(&space,
                                    STACK_TOP - (i + 1) * PAGE64_SIZE, f,
                                    PAGE64_PRESENT | PAGE64_WRITE |
                                    PAGE64_USER) != PAGING64_OK)
                stack_ok = 0;
        }
        check("a stack for it", stack_ok);
        rsp = STACK_TOP - 8;

        serial64_puts("NOVARIS64: initrd  = ");
        serial64_putdec(initrd64_file_count());
        serial64_puts(" file(s), ");
        serial64_putdec(initrd64_size());
        serial64_puts(" bytes\nNOVARIS64: --- its output follows ---\n");

        pf_diagnose = 1;
        vmspace64_switch(&space);
        enter_user_mode64(exe.entry, rsp, 0);
        vmspace64_switch(&kspace);
        pf_diagnose = 0;

        serial64_puts("NOVARIS64: --- end of its output ---\n");

        /* The exit codes are the program's own diagnosis: 11 is success,
         * and each failure path has its own number so a break says which
         * step broke rather than only that something did. */
        check("LoadLibraryA, GetProcAddress and the call all worked",
              syscall64_exit_code() == 11);
        check("exactly one module was mapped",
              win32_64_loads() == loads_before + 1);
        check("and it is registered under the name it was asked for",
              pe64_module_base("dlllib64.dll") != 0);

        serial64_puts("NOVARIS64: exit    = ");
        serial64_putdec(syscall64_exit_code());
        serial64_puts(", modules loaded ");
        serial64_putdec(win32_64_loads() - loads_before);
        serial64_putc('\n');
    }

    /* --- layer 19: a thread, made with clone(2) --------------------- */
    /* The first thing Wine needs that this tree did not have. Two
     * threads in ONE address space, which is what makes it different
     * from Milestone 49's two tasks: those had a space each and could
     * not have shared a variable if they wanted to. */
    serial64_puts("NOVARIS64: -- threads --\n");
    {
        const uint64_t STACK_TOP   = 0x00007FFFFFFF0000ULL;
        const uint64_t STACK_PAGES = 16;
        vmspace64_t kspace, space;
        elf64_info_t info;
        uint64_t i;
        uint64_t written_before = syscall64_bytes_written();
        /* Earlier layers call exit(2) too, so this counts the delta
         * rather than the total. */
        uint64_t exits_before = syscall64_thread_exits();
        int rc, stack_ok = 1, main_tid;
        registers64_t placeholder;

        vmspace64_kernel_space(&kspace);
        check("a space for it", vmspace64_create(&space) != 0);

        rc = elf64_load(thread64_elf, thread64_elf_len, &space, &info);
        check("the threaded program loaded", rc == ELF64_OK);

        for (i = 0; i < STACK_PAGES; i++) {
            uint64_t f = pmm64_alloc_frame();
            if (!f || vmspace64_map(&space,
                                    STACK_TOP - (i + 1) * PAGE64_SIZE, f,
                                    PAGE64_PRESENT | PAGE64_WRITE |
                                    PAGE64_USER) != PAGING64_OK)
                stack_ok = 0;
        }
        check("a stack for it", stack_ok);
        uspace64_reset(&space, info.brk_start);

        /* The main thread has to be a scheduler task before it clones,
         * or there is nothing for the child to be a sibling of. Its
         * frame is a placeholder: the first timer tick overwrites it
         * with the real one before any switch happens. */
        sched64_init();
        for (i = 0; i < sizeof(placeholder) / 8; i++)
            ((uint64_t*)&placeholder)[i] = 0;
        main_tid = sched64_add_frame(&placeholder, &space, 0);
        check("the main thread is a scheduler task", main_tid == 0);
        sched64_set_current(main_tid);

        register_interrupt_handler64(32, sched_timer_handler);
        idt64_irq_set_mask(0, 0);

        serial64_puts("NOVARIS64: --- its output follows ---\n");
        pf_diagnose = 1;
        vmspace64_switch(&space);
        /* The parent spins on a variable only the child writes, so this
         * returns only if the scheduler really ran both. */
        enter_user_mode64(info.entry, STACK_TOP, 0);
        vmspace64_switch(&kspace);
        pf_diagnose = 0;
        idt64_irq_set_mask(0, 1);
        serial64_puts("NOVARIS64: --- end of its output ---\n");

        check("clone created a second thread",
              sched64_current() >= 0 && sched64_switches() > 0);
        check("both threads ran, sharing one address space",
              syscall64_bytes_written() > written_before);
        /* 23 is the parent's own status. 81 or 82 would mean mmap or
         * clone failed; a hang would mean the child never got the CPU. */
        check("the parent saw the child's write and exited cleanly",
              syscall64_exit_code() == 23);
        /* The child called exit(2), which ends a thread. If that were
         * still a synonym for exit_group(2) the run would have ended
         * with the child's status and the parent would never have
         * printed - which is exactly how Linux caught this. */
        check("the child ended as a thread, not as the process",
              syscall64_thread_exits() == exits_before + 1);

        serial64_puts("NOVARIS64: switches= ");
        serial64_putdec(sched64_switches());
        serial64_puts(", exit ");
        serial64_putdec(syscall64_exit_code());
        serial64_putc('\n');
    }

    /* --- layer 20: a futex ------------------------------------------ */
    /* thread64.s spun. This one sleeps, which is the difference that
     * matters: a kernel implementing FUTEX_WAIT as "return 0" would
     * still pass that test - the parent would loop again - and cannot
     * pass this one, because there is no loop to fall back into. */
    serial64_puts("NOVARIS64: -- futex --\n");
    {
        const uint64_t STACK_TOP   = 0x00007FFFFFFF0000ULL;
        const uint64_t STACK_PAGES = 16;
        vmspace64_t kspace, space;
        elf64_info_t info;
        uint64_t i;
        uint64_t written_before = syscall64_bytes_written();
        uint64_t waits_before   = syscall64_futex_waits();
        uint64_t wakes_before   = syscall64_futex_wakes();
        int rc, stack_ok = 1, main_tid;
        registers64_t placeholder;

        vmspace64_kernel_space(&kspace);
        check("a space for it", vmspace64_create(&space) != 0);

        rc = elf64_load(futex64_elf, futex64_elf_len, &space, &info);
        check("the futex program loaded", rc == ELF64_OK);

        for (i = 0; i < STACK_PAGES; i++) {
            uint64_t f = pmm64_alloc_frame();
            if (!f || vmspace64_map(&space,
                                    STACK_TOP - (i + 1) * PAGE64_SIZE, f,
                                    PAGE64_PRESENT | PAGE64_WRITE |
                                    PAGE64_USER) != PAGING64_OK)
                stack_ok = 0;
        }
        check("a stack for it", stack_ok);
        uspace64_reset(&space, info.brk_start);

        sched64_init();
        for (i = 0; i < sizeof(placeholder) / 8; i++)
            ((uint64_t*)&placeholder)[i] = 0;
        main_tid = sched64_add_frame(&placeholder, &space, 0);
        sched64_set_current(main_tid);

        register_interrupt_handler64(32, sched_timer_handler);
        idt64_irq_set_mask(0, 0);

        serial64_puts("NOVARIS64: --- its output follows ---\n");
        pf_diagnose = 1;
        vmspace64_switch(&space);
        enter_user_mode64(info.entry, STACK_TOP, 0);
        vmspace64_switch(&kspace);
        pf_diagnose = 0;
        idt64_irq_set_mask(0, 1);
        sched64_init();
        serial64_puts("NOVARIS64: --- end of its output ---\n");

        check("the handoff happened",
              syscall64_bytes_written() > written_before);
        check("and the program exited with its own status, 31",
              syscall64_exit_code() == 31);
        /* Without these two the run proves nothing: a parent that never
         * contended would take the fast path, never sleep, and pass
         * every assertion above. */
        check("a thread really blocked in futex(2)",
              syscall64_futex_waits() > waits_before);
        check("and a wakeup really woke one",
              syscall64_futex_wakes() > wakes_before);

        serial64_puts("NOVARIS64: waits   = ");
        serial64_putdec(syscall64_futex_waits() - waits_before);
        serial64_puts(", wakes ");
        serial64_putdec(syscall64_futex_wakes() - wakes_before);
        serial64_puts(", exit ");
        serial64_putdec(syscall64_exit_code());
        serial64_putc('\n');
    }

    /* --- layer 21: a signal handler that resumes elsewhere ---------- */
    /* Wine's exception dispatch in miniature: take SIGSEGV, read the
     * saved registers out of the ucontext, write RIP back, carry on.
     * Every layer before this treated a ring-3 fault as the end of the
     * program. */
    serial64_puts("NOVARIS64: -- signals --\n");
    {
        const uint64_t STACK_TOP   = 0x00007FFFFFFF0000ULL;
        const uint64_t STACK_PAGES = 16;
        vmspace64_t kspace, space;
        elf64_info_t info;
        uint64_t i;
        uint64_t written_before = syscall64_bytes_written();
        int rc, stack_ok = 1;

        vmspace64_kernel_space(&kspace);
        signal64_reset();
        check("a space for it", vmspace64_create(&space) != 0);

        rc = elf64_load(signal64_elf, signal64_elf_len, &space, &info);
        check("the signal program loaded", rc == ELF64_OK);

        for (i = 0; i < STACK_PAGES; i++) {
            uint64_t f = pmm64_alloc_frame();
            if (!f || vmspace64_map(&space,
                                    STACK_TOP - (i + 1) * PAGE64_SIZE, f,
                                    PAGE64_PRESENT | PAGE64_WRITE |
                                    PAGE64_USER) != PAGING64_OK)
                stack_ok = 0;
        }
        check("a stack for it", stack_ok);
        uspace64_reset(&space, info.brk_start);

        /* pf_diagnose stays OFF: this program is *supposed* to fault,
         * and the diagnostic path halts the machine. */
        serial64_puts("NOVARIS64: --- its output follows ---\n");
        vmspace64_switch(&space);
        enter_user_mode64(info.entry, STACK_TOP, 0);
        vmspace64_switch(&kspace);
        serial64_puts("NOVARIS64: --- end of its output ---\n");

        check("the fault reached a ring-3 handler",
              signal64_delivered() == 1);
        check("and the handler returned through rt_sigreturn",
              signal64_returns() == 1);
        check("the program resumed and printed",
              syscall64_bytes_written() > written_before);
        /* 41 is only reachable through the resume path: the faulting
         * instruction is followed by nothing else that leads there. */
        check("it exited with the status that means it recovered",
              syscall64_exit_code() == 41);

        serial64_puts("NOVARIS64: signals = ");
        serial64_putdec(signal64_delivered());
        serial64_puts(" delivered, ");
        serial64_putdec(signal64_returns());
        serial64_puts(" returned, exit ");
        serial64_putdec(syscall64_exit_code());
        serial64_putc('\n');
    }

    /* --- layer 22: a writable filesystem ---------------------------- */
    /* Milestone 54's initrd could be read. This one can be written to,
     * which is the difference that matters: a Wine prefix is thousands
     * of files Wine *creates*. */
    serial64_puts("NOVARIS64: -- a writable filesystem --\n");
    {
        const uint64_t STACK_TOP   = 0x00007FFFFFFF0000ULL;
        const uint64_t STACK_PAGES = 16;
        vmspace64_t kspace, space;
        elf64_info_t info;
        uint64_t i;
        uint64_t written_before = syscall64_bytes_written();
        int rc, stack_ok = 1;

        ramfs64_init();
        ramfs64_seed_from_initrd();
        syscall64_reset_files();

        check("the filesystem came up with /tmp", ramfs64_lookup("/tmp") >= 0);
        /* Whatever the initrd held is still readable, so this milestone
         * adds writing rather than replacing reading. */
        check("and the initrd's contents were carried into it",
              ramfs64_lookup("/dlllib64.dll") >= 0);

        vmspace64_kernel_space(&kspace);
        check("a space for it", vmspace64_create(&space) != 0);

        rc = elf64_load(fs64_elf, fs64_elf_len, &space, &info);
        check("the filesystem program loaded", rc == ELF64_OK);

        for (i = 0; i < STACK_PAGES; i++) {
            uint64_t f = pmm64_alloc_frame();
            if (!f || vmspace64_map(&space,
                                    STACK_TOP - (i + 1) * PAGE64_SIZE, f,
                                    PAGE64_PRESENT | PAGE64_WRITE |
                                    PAGE64_USER) != PAGING64_OK)
                stack_ok = 0;
        }
        check("a stack for it", stack_ok);
        uspace64_reset(&space, info.brk_start);

        serial64_puts("NOVARIS64: --- its output follows ---\n");
        pf_diagnose = 1;
        vmspace64_switch(&space);
        enter_user_mode64(info.entry, STACK_TOP, 0);
        vmspace64_switch(&kspace);
        pf_diagnose = 0;
        serial64_puts("NOVARIS64: --- end of its output ---\n");

        check("the program said so too",
              syscall64_bytes_written() > written_before);
        /* Each failure path in the program has its own status - 71 is a
         * failed open, 75 a mismatched read-back, 77 a file that
         * survived being unlinked - so a break says which step broke. */
        check("open, write, seek, read-back, unlink all worked",
              syscall64_exit_code() == 53);
        check("and the file it removed is gone",
              ramfs64_lookup("/tmp/novaris-fs-test") < 0);

        serial64_puts("NOVARIS64: fs      = ");
        serial64_putdec(ramfs64_count());
        serial64_puts(" nodes, exit ");
        serial64_putdec(syscall64_exit_code());
        serial64_putc('\n');
    }

    /* --- verdict ---------------------------------------------------- */
    serial64_puts("NOVARIS64: failures = ");
    serial64_putdec((uint64_t)failures);
    serial64_putc('\n');
    serial64_puts("NOVARIS64: ---- bring-up complete ----\n");

    for (;;) __asm__ __volatile__("hlt");
}
