#ifndef FONT8X16_H
#define FONT8X16_H

#include <stdint.h>

/* Covers printable ASCII 32 ('space') through 126 ('~'). Index into
 * font8x16[] with (c - FONT8X16_FIRST_CHAR); anything outside that range
 * isn't included (see console.c, which falls back to a blank glyph). */
#define FONT8X16_FIRST_CHAR 32
#define FONT8X16_LAST_CHAR  126
#define FONT8X16_NGLYPHS    (FONT8X16_LAST_CHAR - FONT8X16_FIRST_CHAR + 1)

/* Generated by tools/gen_font.py - see kernel/font8x16.c. Each glyph is
 * 16 bytes, one per row, 8 pixels per row (MSB = leftmost pixel). */
extern const uint8_t font8x16[FONT8X16_NGLYPHS][16];

#endif
