#ifndef TASK_B_H
#define TASK_B_H

/* Generated by userland/embed_tasks.py from userland/task_b.bin - see
 * kernel/task_b_blob.c. Tiny demo ring-3 program for Milestone 9's
 * preemptive scheduler (see kernel/scheduler.c and the shell's
 * 'multitask' command). */
extern const unsigned char task_b_bin[];
extern const unsigned int task_b_bin_len;

#endif
