#ifndef TASK_A_H
#define TASK_A_H

/* Generated by userland/embed_tasks.py from userland/task_a.bin - see
 * kernel/task_a_blob.c. Tiny demo ring-3 program for Milestone 9's
 * preemptive scheduler (see kernel/scheduler.c and the shell's
 * 'multitask' command). */
extern const unsigned char task_a_bin[];
extern const unsigned int task_a_bin_len;

#endif
