#ifndef TASK_C_H
#define TASK_C_H

/* Generated by userland/embed_tasks.py from userland/task_c.bin - see
 * kernel/task_c_blob.c. Tiny demo ring-3 program for Milestone 9's
 * preemptive scheduler (see kernel/scheduler.c and the shell's
 * 'multitask' command). */
extern const unsigned char task_c_bin[];
extern const unsigned int task_c_bin_len;

#endif
