#ifndef THREAD_DEMO_H
#define THREAD_DEMO_H

/* Generated by userland/embed_tasks.py from userland/thread_demo.bin -
 * see kernel/thread_demo_blob.c. One image, run by two scheduler tasks
 * sharing one address space; see the source for what it proves. */
extern const unsigned char thread_demo_bin[];
extern const unsigned int thread_demo_bin_len;

/* Offsets into the image the kernel has to know, because a flat binary
 * carries no symbol table. Must match userland/thread_demo.s. */
#define THREAD_DEMO_THREAD1_ENTRY 0x40u
#define THREAD_DEMO_COUNTER       0x200u
#define THREAD_DEMO_ITERATIONS    8u

#endif
