#ifndef USER_HELLO_H
#define USER_HELLO_H

/* Generated by userland/embed.py from userland/user_hello.bin - see
 * kernel/user_hello_blob.c. */
extern const unsigned char user_hello_bin[];
extern const unsigned int user_hello_bin_len;

#endif
