#!/usr/bin/env python3
"""Generates kernel/font8x16.c: an 8x16 monochrome bitmap font for ASCII
32-126, rendered from DejaVu Sans Mono (Bitstream Vera Fonts License -
permits embedding/redistribution/modification) and thresholded to 1bpp.

Regenerate with: python3 tools/gen_font.py
"""
from PIL import Image, ImageDraw, ImageFont

FONT_PATH = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"
CHAR_W, CHAR_H = 8, 16
FIRST, LAST = 32, 126  # inclusive, printable ASCII

font = ImageFont.truetype(FONT_PATH, 13)

glyphs = []
for code in range(FIRST, LAST + 1):
    ch = chr(code)
    img = Image.new("L", (CHAR_W, CHAR_H), 0)
    draw = ImageDraw.Draw(img)
    bbox = font.getbbox(ch)
    w = bbox[2] - bbox[0] if bbox else 0
    x = max(0, (CHAR_W - w) // 2 - (bbox[0] if bbox else 0))
    draw.text((x, 1), ch, fill=255, font=font)
    rows = []
    for y in range(CHAR_H):
        byte = 0
        for x in range(CHAR_W):
            px = img.getpixel((x, y))
            bit = 1 if px > 90 else 0
            byte = (byte << 1) | bit
        rows.append(byte)
    glyphs.append((code, rows))

out_path = "/home/claude/novaris/kernel/font8x16.c"
with open(out_path, "w") as f:
    f.write("/* GENERATED by tools/gen_font.py - do not edit by hand.\n")
    f.write(" * 8x16 monochrome bitmap font, ASCII 32-126, rendered from DejaVu\n")
    f.write(" * Sans Mono (Bitstream Vera Fonts License - explicitly permits\n")
    f.write(" * embedding and redistribution of modified/rendered forms) and\n")
    f.write(" * thresholded to 1 bit per pixel. Regenerate with:\n")
    f.write(" *   python3 tools/gen_font.py */\n\n")
    f.write('#include "font8x16.h"\n\n')
    f.write(f"const uint8_t font8x16[FONT8X16_NGLYPHS][16] = {{\n")
    for code, rows in glyphs:
        ch_repr = repr(chr(code))
        row_str = ", ".join(f"0x{b:02x}" for b in rows)
        f.write(f"    {{ {row_str} }}, /* {code} {ch_repr} */\n")
    f.write("};\n")

print(f"wrote {out_path}: {len(glyphs)} glyphs")
