#!/usr/bin/env python3
"""Generates kernel/uifont.c: the antialiased proportional UI typeface the
desktop draws with.

Milestone 7's font8x16 is a 1-bit monospaced 8x16 grid, which is exactly
right for a terminal and exactly wrong for window titles, menus and Dock
labels - proportional text at that resolution needs real coverage values,
not thresholded bits, or every diagonal turns into a staircase.

So this renders four faces to 8-bit alpha coverage maps with per-glyph
bearings and advances (i.e. the small subset of a font engine the compositor
actually needs), and emits them as C arrays. kernel/gfx.c blends them.

Source face: DejaVu Sans (Bitstream Vera Fonts License, which explicitly
permits embedding and redistribution of modified/rendered forms) - the same
family, and the same licensing reasoning, as tools/gen_font.py.

Regenerate with:  python3 tools/gen_uifont.py
"""

import os

from PIL import Image, ImageDraw, ImageFont

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SANS = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
SANS_BOLD = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"

# name, ttf path, pixel size
FACES = [
    ("uifont_small", SANS, 11),
    ("uifont_regular", SANS, 13),
    ("uifont_bold", SANS_BOLD, 13),
    ("uifont_title", SANS_BOLD, 22),
]

FIRST, LAST = 1, 126

# Control codes 1-15 carry the UI symbols, so a plain C string literal can
# say "\x01Q" and get a command-key glyph. 8/9/10/13 are deliberately left
# empty: they are \b \t \n \r and pass through code that acts on them.
SYMBOLS = {
    0x01: "⌘",  # place of interest / command
    0x02: "⌥",  # option
    0x03: "⇧",  # shift
    0x04: "⌃",  # control
    0x05: "✓",  # check mark
    0x06: "▸",  # small right triangle (submenu arrow)
    0x07: "●",  # filled circle (running indicator)
    0x0b: "•",  # bullet
    0x0c: "…",  # ellipsis
    0x0e: "→",  # right arrow
    0x0f: "≡",  # identical to (hamburger-ish menu mark)
    0x10: "—",  # em dash, for window titles like "novaris — shell"
    0x11: "⌫",  # delete
}


def char_for(code):
    if code in SYMBOLS:
        return SYMBOLS[code]
    if 32 <= code <= 126:
        return chr(code)
    return None


def render_face(path, size):
    font = ImageFont.truetype(path, size)
    ascent, descent = font.getmetrics()
    pad = size * 2

    glyphs = []
    blob = bytearray()
    for code in range(FIRST, LAST + 1):
        ch = char_for(code)
        if ch is None:
            glyphs.append((0, 0, 0, 0, 0, 0))
            continue

        advance = int(round(font.getlength(ch)))
        img = Image.new("L", (size * 4 + pad * 2, size * 4 + pad * 2), 0)
        draw = ImageDraw.Draw(img)
        # anchor="ls": pen at the left edge, on the baseline - the same
        # origin convention the C renderer uses.
        draw.text((pad, pad + ascent), ch, fill=255, font=font, anchor="ls")
        bbox = img.getbbox()
        if bbox is None:  # whitespace: advance only, no pixels
            glyphs.append((0, 0, 0, 0, 0, advance))
            continue

        x0, y0, x1, y1 = bbox
        crop = img.crop(bbox)
        offset = len(blob)
        blob.extend(crop.tobytes())
        glyphs.append((offset, x1 - x0, y1 - y0, x0 - pad, (pad + ascent) - y0,
                       advance))

    return {
        "ascent": ascent,
        "descent": descent,
        "line_height": ascent + descent,
        "glyphs": glyphs,
        "blob": blob,
    }


def emit(out, name, face):
    out.write("/* --- %s: %d glyphs, %d bytes of coverage ------------ */\n"
              % (name, len(face["glyphs"]), len(face["blob"])))
    out.write("static const uint8_t %s_pixels[] = {\n" % name)
    blob = face["blob"]
    for i in range(0, len(blob), 16):
        row = ", ".join("0x%02x" % b for b in blob[i:i + 16])
        out.write("    %s,\n" % row)
    out.write("};\n\n")

    out.write("static const uifont_glyph_t %s_glyphs[] = {\n" % name)
    for code, g in zip(range(FIRST, LAST + 1), face["glyphs"]):
        offset, w, h, left, top, advance = g
        label = repr(chr(code)) if 32 <= code <= 126 else "0x%02x" % code
        out.write("    { %5d, %2d, %2d, %3d, %3d, %2d }, /* %s */\n"
                  % (offset, w, h, left, top, advance, label))
    out.write("};\n\n")

    out.write("const uifont_t %s = {\n" % name)
    out.write("    %d, %d, %d, %d, %d,\n"
              % (FIRST, LAST, face["ascent"], face["descent"],
                 face["line_height"]))
    out.write("    %s_glyphs, %s_pixels\n};\n\n" % (name, name))


def main():
    faces = [(name, render_face(path, size)) for name, path, size in FACES]

    out_path = os.path.join(HERE, "kernel", "uifont.c")
    with open(out_path, "w") as out:
        out.write("/* GENERATED by tools/gen_uifont.py - do not edit by hand.\n"
                  " *\n"
                  " * Antialiased proportional UI faces for the desktop: 8-bit\n"
                  " * coverage maps plus per-glyph bearings and advances,\n"
                  " * rendered from DejaVu Sans / DejaVu Sans Bold (Bitstream\n"
                  " * Vera Fonts License, which explicitly permits embedding and\n"
                  " * redistribution of rendered/modified forms).\n"
                  " *\n"
                  " * Regenerate with: python3 tools/gen_uifont.py */\n\n")
        out.write('#include "uifont.h"\n\n')
        for name, face in faces:
            emit(out, name, face)

    total = sum(len(f["blob"]) for _, f in faces)
    print("wrote %s: %d faces, %d bytes of glyph coverage"
          % (out_path, len(faces), total))
    for (name, _, size), (_, face) in zip(FACES, faces):
        print("  %-16s %2dpx  ascent %2d  descent %d  %6d bytes"
              % (name, size, face["ascent"], face["descent"], len(face["blob"])))


if __name__ == "__main__":
    main()
