#!/usr/bin/env python3
"""Writes the update manifest for a build.

    tools/make_manifest.py <build-dir> <base-url> <version> [name]

Milestone 40. `update` in the guest fetches one of these, and refuses any
download whose size or checksum does not match what it says. So this is
the file that decides what a machine will accept - which is why it is
generated from the images rather than written by hand: a manifest whose
checksums are typed in is a manifest that is wrong the first time
somebody rebuilds and forgets.

The checksum is FNV-1a 32, because that is what the kernel already
computes for `sum` and what its updater already has code for. It is a
*hash*, not a signature: it catches a truncated download and a corrupted
one, and it catches nothing at all about who served it. See the note in
include/update.h.
"""

import os
import sys


def fnv1a(data):
    h = 2166136261
    for b in data:
        h = ((h ^ b) * 16777619) & 0xFFFFFFFF
    return h


def main(argv):
    if len(argv) not in (4, 5):
        sys.stderr.write(__doc__)
        return 2

    build_dir, base_url, version = argv[1], argv[2].rstrip("/"), argv[3]
    name = argv[4] if len(argv) > 4 else "Novaris %s" % version

    kernel_path = os.path.join(build_dir, "novaris.bin")
    initrd_path = os.path.join(build_dir, "initrd.img")

    for path in (kernel_path, initrd_path):
        if not os.path.exists(path):
            sys.stderr.write("missing: %s (run make first)\n" % path)
            return 1

    kernel = open(kernel_path, "rb").read()
    initrd = open(initrd_path, "rb").read()

    out = [
        "# Novaris update manifest, generated by tools/make_manifest.py",
        "version     = %s" % version,
        "name        = %s" % name,
        "kernel      = %s/novaris.bin" % base_url,
        "kernel_size = %d" % len(kernel),
        "kernel_sum  = %08x" % fnv1a(kernel),
        "initrd      = %s/initrd.img" % base_url,
        "initrd_size = %d" % len(initrd),
        "initrd_sum  = %08x" % fnv1a(initrd),
        "",
    ]
    sys.stdout.write("\n".join(out))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
